### PR TITLE
[Feature #157733029] Admin can see details of a request.

### PR DESCRIPTION
**Pull request by mmosoroohh**
#### What does this PR do?
Completed the frontend design for a page where an admin can:
-  view details of a particular request
- Give feedback
-  Approve, resolved or decline a request

#### Description of tasks to be completed
- Navigation bar
- A card where an admin can view details of the request.
- Feedback card where an admin can give a response to that particular request approved or declined.

#### How should this be manually tested?
- Clone or download the repository.
- Navigate to the UI directory and open the view.html file on a browser to access it.

#### Any background context you want to provide?
CSS stylesheet

#### What are the relevant Pivotal Tracker Stories?

[#157733029](https://www.pivotaltracker.com/n/projects/2173237)
[#157732994](https://www.pivotaltracker.com/n/projects/2173237)
[#157733084](https://www.pivotaltracker.com/n/projects/2173237)
[#157733199](https://www.pivotaltracker.com/n/projects/2173237)

#### Screenshot (if appropriate)
screenshot from 2018-05-27 13-06-38

### CODE REVIEW

**Comment by Melvin1Atieno** [comment]
Niiiice!!! see whether you can make the fonts bigger

**Comment by mmosoroohh** [comment]
Thanks...
I'll work on it.

**Comment by asamisellah** [comment]
PR up to standard. How does the admin approve/ reject a request in your design?

**Comment by mmosoroohh** [comment]
@asamisellah Thank you...
On the feedback card after filling the feedback, the select button after gives you an option to approve, decline or resolved.

**Comment by denniswanjiru** [comment]
Nice ui.  I guess it's not a good idea to put pt stories links as your commit messages.

**Comment by mmosoroohh** [comment]
@DennisWanjiru Thank you...
Yeah, it is not. Making it short and precise is good.

**Pull request closed without merging**
